language: cpp

os: linux
dist: trusty
sudo: required

addons:
  apt:
    packages:
      - libssl-dev
      - libboost-dev
      - cmake
      - checkinstall

matrix:
  include:
    - env: "_config=debug_cxx98"
    - env: "_config=debug_cxx11"
    - env: "_config=optimized_debug_cxx98"
    - env: "_config=optimized_debug_cxx11"
    - env: "_config=release_cxx98"
    - env: "_config=release_cxx11"

before_install:
  - "pushd third"
  - "./build_mysql-connector-c_deb.sh"
  - "./build_mongo-c-driver_deb.sh"
  - "popd"

install:
  - "./reconfig_${_config}.sh"
  - "make -j$(nproc)"
  - "make check"

script:
  - "exit 0"

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#mcfproj"
    template:
      - "[ lh_mouse %{repository_slug}#%{commit}] %{result} on %{branch} by %{author} (%{build_url})"
  email: false
